### PR TITLE
fix: Extend template directives functionality

### LINKED ISSUE #2468: Template directives do not appear to work correctly on templates within `.chezmoitemplates`
## Describe the bug

I'm currently updating [my chezmoi Firefox setup sample repo](https://github.com/bradenhilton/chezmoi-firefox-setup) in anticipation of template directive support being released.

I'm testing on the latest master commit (https://github.com/twpayne/chezmoi/commit/5d0c9677413eaffb86bd0678fd0acdfcb1cd6011 at time of writing).

The template directives either result in chezmoi exiting with an error, or the template result is mangled.

## To reproduce

Here are a few example source states to test with, along with their outputs:

<details>
<summary><code>directives-test/js/</code></summary>

`.chezmoitemplates/example.js`:

```javascript
// chezmoi:template:left-delimiter=//{{
//{{- if eq .chezmoi.os "windows" -}}
console.log("windows");
//{{- else -}}
console.log("not windows");
//{{- end -}}
```

`example.js.tmpl`:

```javascript
// chezmoi:template:left-delimiter=//{{
//{{- template "example.js" . -}}
```

```console
❯ .\chezmoi.exe -S .\directives-test\js -D .\dest diff
chezmoi: template: example.js:2: unexpected "/" in command
```

If I surround the delimiter in double quotes:

```console
❯ .\chezmoi.exe -S .\directives-test\js -D .\dest diff
chezmoi: template: example.js:1: unterminated quoted string
```

</details>

<details>
<summary><code>directives-test/css/</code></summary>

`.chezmoitemplates/example.css`:

```css
/* chezmoi:template:left-delimiter=/*{{ right-delimiter=}}*/
/*{{- if eq .chezmoi.os "windows" -}}*/
body {
    background-color: blue;
}
/*{{- else -}}*/
body {
    background-color: red;
}
/*{{- end -}}*/
```

`example.css.tmpl`:

```css
/* chezmoi:template:left-delimiter=/*{{ right-delimiter=}}*/
/*{{- template "example.css" . -}}*/
```

```console
❯ .\chezmoi.exe -S .\directives-test\css -D .\dest diff
chezmoi: template: example.css:1: bad character U+002D '-'
```

</details>

<details>
<summary><code>directives-test/default-quoted/</code></summary>

`.chezmoitemplates/example.txt`:

```
chezmoi:template:left-delimiter="{{" right-delimiter="}}"
{{- if eq .chezmoi.os "windows" -}}
windows
{{- else -}}
not windows
{{- end -}}
```

`example.txt.tmpl`:

```
chezmoi:template:left-delimiter="{{" right-delimiter="}}"
{{- template "example.txt" . -}}
```

```console
❯ .\chezmoi.exe -S .\directives-test\default-quoted -D .\dest diff
diff --git a/example.txt b/example.txt
new file mode 100666
index 0000000000000000000000000000000000000000..6325c8d5b1faa34a33a1669686839b0e495eb64f
--- /dev/null
+++ b/example.txt
@@ -0,0 +1 @@
+chezmoi:template:left-delimiter=" right-delimiter="windows
\ No newline at end of file
```

In this example, it looks like `<space>right-delimiter=` is being pasted as a string after being parsed with the default delimiters.

</details>

All of these work correctly if I move the `.chezmoitemplates/**` content directly into the `.tmpl` files.

## Expected behavior

Template directives should correctly act upon templates within `.chezmoitemplates`.

## Output of command with the `--verbose` flag

NA. Same output as above.

## Output of `chezmoi doctor`

<details>

```console
❯ .\chezmoi.exe doctor
RESULT    CHECK                MESSAGE
warning   version              dev, commit 5d0c9677413eaffb86bd0678fd0acdfcb1cd6011-dirty, built at 2022-10-18T00:11:17Z
warning   latest-version       v2.25.0
ok        os-arch              windows/amd64
ok        systeminfo           Microsoft Windows 10 Pro (10.0.19044 N/A Build 19044)
ok        go-version           go1.19.1 (gc)
ok        executable           D:/Dev/Git/chezmoi-twpayne/chezmoi.exe
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-10-16T22:34:03+01:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        cd-command           found C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
ok        cd-args              powershell -NoLogo
info      diff-command         not set
ok        edit-command         found C:/Windows/system32/notepad.exe
ok        edit-args            'C:\\Windows\\system32\\notepad.exe'
ok        git-command          found C:/Program Files/Git/cmd/git.exe, version 2.38.0
warning   merge-command        vimdiff not found in $PATH
ok        shell-command        found C:/WINDOWS/system32/cmd.exe
ok        shell-args           'C:\\WINDOWS\\system32\\cmd.exe'
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found ~/scoop/shims/bw.exe, version 2022.10.0
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

https://github.com/twpayne/chezmoi/pull/2457#issuecomment-1282941114

### PR DESCRIPTION
**Pull request by halostatue**
Fixes #2468

Template directives have been added, but some places were missed in the initial implementation and review (oops).

- pkg/cmd/templatefuncs.go (`includeTemplateTemplateFunc`)
- pkg/chezmoi/sourcestate.go (`addTemplatesDir`)
- pkg/cmd/config.go (`createConfigFile`)
- pkg/cmd/config.go (`gitautoCommit`)

The last is not necessary (since the template is only included as an asset and cannot be replaced), so it can be reversed without issue.

### CODE REVIEW

**Comment by halostatue** [comment]
@bradenhilton This should resolve the issue.

**Comment by halostatue** [comment]
@twpayne The approach that I took might be a bit controversial, but it seemed better than the duplication I was seeing and implementing. The name of the function is *definitely* something worth considering whether it’s the right thing.

File: pkg/chezmoi/sourcestate.go [hunk 1]
```diff
@@ -2179,6 +2181,29 @@ func (e *External) OriginString() string {
...
+	funcs template.FuncMap,
+	options ...TemplateOptions,
+) (*template.Template, error) {
+	var o TemplateOptions
+
+	if len(options) > 0 {
+		o = options[0]
+	} else {
+		o = TemplateOptions{}
+	}
```
Comment (twpayne) [inline pkg/chezmoi/sourcestate.go:2196]: This will silently ignore any `TemplateOptions`after the first one. Instead, I'd suggest that the caller passes the address of an existing struct if they don't want a zero-valued `TemplateOptions`, or `nil` if they do:

```go
func NewConfiguredTemplate(
	name string,
	data []byte,
	funcs template.FuncMap,
	options *TemplateOptions,
) (*template.Template, error) {
	var o TemplateOptions
	if options != nil {
		o = *options
	}
	// ...
}
```

Comment (halostatue) [reply pkg/chezmoi/sourcestate.go:2196]: Yeah. I was trying to avoid the explicit `nil` in this case.
