### PR TITLE
fix: `lookPath` panics when file does not exists

### LINKED ISSUE #1606: Template function "lookPath" errors when file is not found
## Describe the bug

The template function `lookPath` produces an error instead of returning an empty string when the file is not found.

Refer to the documentation, which states:

> If _file_ is not found, lookPath returns an empty string.

https://www.chezmoi.io/docs/reference/#lookpath-file

```sh
❯ chezmoi apply
chezmoi: template: dot_zshenv.tmpl:3:7: executing "dot_zshenv.tmpl" at <lookPath (joinPath .chezmoi.homeDir "/.cargo/env")>: error calling lookPath: exec: "/home/thomas/.cargo/env": stat /home/thomas/.cargo/env: no such file or directory
```

## To reproduce

Create a template file which uses `lookPath` to search for a non-existent file.

```tmpl
{{- if lookPath (joinPath .chezmoi.homeDir "/.cargo/env") }}
. $HOME/.cargo/env
{{- end }}
```

Apply the changes with chezmoi and observe aforementioned error.

## Expected behaviour

`lookPath` should conform to the documentation and return an empty string.

## Output of command with the `--verbose` flag

```sh
❯ chezmoi apply -v
chezmoi: template: dot_zshenv.tmpl:3:7: executing "dot_zshenv.tmpl" at <lookPath (joinPath .chezmoi.homeDir "/.cargo/env")>: error calling lookPath: exec: "/home/thomas/.cargo/env": stat /home/thomas/.cargo/env: no such file or directory
```

## Output of `chezmoi doctor`

```sh
❯ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.7.5, built at 2021-11-08T11:20:41Z
ok        os-arch              linux/amd64 (Arch Linux)
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /usr/bin/zsh
ok        edit-command         found /usr/bin/vim
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.33.1
ok        merge-command        found /usr/bin/vimdiff
failed    age-command          found /usr/bin/age, could not parse version from (devel)
ok        gpg-command          found /usr/bin/gpg, version 2.2.29
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

## Additional context

None.

### PR DESCRIPTION
**Pull request by felipecrs**
When it should just return an empty string, specifically when looking for an absolute path.

Fixes #1606

### CODE REVIEW

File: internal/cmd/templatefuncs.go [hunk 1]
```diff
@@ -73,6 +73,8 @@ func (c *Config) lookPathTemplateFunc(file string) string {
 		return path
 	case errors.Is(err, exec.ErrNotFound):
 		return ""
```
Comment (twpayne) [inline internal/cmd/templatefuncs.go:75]: I think the above two lines can be removed.

File: internal/cmd/testdata/scripts/templatefuncs.txt [hunk 2]
```diff
@@ -27,10 +27,14 @@ cmp stdout golden/include-relpath
...
 stdout a${/}b
 
-# test lookPath template function
+# test lookPath template function to find in PATH
 chezmoi execute-template '{{ lookPath "go" }}'
 stdout go$exe
 
+# test lookPath template function to check if file exists
+chezmoi execute-template '{{ lookPath "/non-existing-file" }}'
+stdout ''
```
Comment (twpayne) [inline internal/cmd/testdata/scripts/templatefuncs.txt:36]: This check isn't quite correct: `stdout` matches the output with a regular expression, and the empty regular expression matches everything. Instead this line should be:
```
! stdout .
```
to check that the output is empty.

**Review by twpayne — CHANGES_REQUESTED** [review]
Thanks for this :) Two minor changes needed.

File: internal/cmd/templatefuncs.go (hunk 1 above)
Comment (felipecrs) [reply internal/cmd/templatefuncs.go:75]: the exec.ErrNotFound? No, it's expected too:

https://github.com/golang/go/blob/master/src/os/exec/lp_unix.go#L58

File: internal/cmd/testdata/scripts/templatefuncs.txt (hunk 2 above)
Comment (felipecrs) [reply internal/cmd/testdata/scripts/templatefuncs.txt:36]: Thank you very much for this. Indeed I didn't search, I just putted whatever came to my mind first :)

File: internal/cmd/templatefuncs.go (hunk 1 above)
Comment (felipecrs) [reply internal/cmd/templatefuncs.go:75]: BTW and FYI: https://github.com/golang/go/pull/49492

File: internal/cmd/testdata/scripts/templatefuncs.txt (hunk 2 above)
Comment (felipecrs) [reply internal/cmd/testdata/scripts/templatefuncs.txt]: Well, it does not seem to work. :(

Comment (felipecrs) [reply internal/cmd/testdata/scripts/templatefuncs.txt]: `stdout '^$'` did the trick.

**Comment by felipecrs** [comment]
Well, I'm not sure if CI is failing because of my change...

File: internal/cmd/doctorcmd.go [hunk 3]
```diff
@@ -187,7 +187,7 @@ func (c *Config) runDoctorCmd(cmd *cobra.Command, args []string) error {
 			name:        "age-command",
 			binaryname:  c.Age.Command,
 			versionArgs: []string{"-version"},
-			versionRx:   regexp.MustCompile(`v(\d+\.\d+\.\d+\S*)`),
+			versionRx:   regexp.MustCompile(`(v\d+\.\d+\.\d+\S*)|(\(devel\))`),
```
Comment (twpayne) [inline internal/cmd/doctorcmd.go:190]: This seems unrelated to this PR.

File: internal/cmd/templatefuncs.go (hunk 1 above)
Comment (twpayne) [reply internal/cmd/templatefuncs.go:75]: Awesome, thanks!

**Comment by twpayne** [comment]
> Well, I'm not sure if CI is failing because of my change...

They're failing because of the change to age version regexp change in `doctorcmd.go`.

File: internal/cmd/doctorcmd.go (hunk 3 above)
Comment (felipecrs) [reply internal/cmd/doctorcmd.go:190]: Wow, I was playing with it and not even noticed it!

**Review by twpayne — APPROVED** [review]
Perfect, thank you :)
